services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - API_URL=${API_URL}
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./backend:/usr/src/app:cached
      - backend_node_modules:/usr/src/app/node_modules
      - ./backend/src/uploads:/usr/src/app/src/uploads
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
      - CLIENT_HOST=${CLIENT_HOST}
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
  frontend_node_modules:
  backend_node_modules: